url: https://bu-bioinfo.github.io/bmsip
title: "BMSIP - BU Bioinformatics Masters Summer Internship Program"
show_downloads: false
lsi: false
safe: true
source: .
ignore_theme_config: true
incremental: false
highlighter: rouge
exclude:
  - asset_sources
  - Gemfile
  - Gemfile.lock
  - serve.sh
  - readme.txt
  - .idea
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-theme-dinky
collections:
  news:
    output: true
    permalink: /:path
  projects:
    output: true
    permalink: /:path
defaults:
  -
    scope:
      path: "_news"
    values:
      layout: "post"
  -
    scope:
      path: "_projects"
    values:
      layout: "project"
  -
    scope:
        path: ""
    values:
        layout: "default"